version: '3.8'

services:
  konspekty:
    image: konspekty:latest
    container_name: konspekty
    network_mode: host
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/opt/app:delegated
